version: "3.8"
name: "course_planner"
services:
  cp_keycloak:
    image: "quay.io/keycloak/keycloak:23.0.7"
    command: ["start-dev"]
    container_name: cp_keycloak
    ports:
      - "8080:8080"
    environment:
      KEYCLOAK_ADMIN: "admin"
      KEYCLOAK_ADMIN_PASSWORD: "XTKItlUh732yujXZoy9Z4aOblY3IEHvS"
    restart: "no"
