# Use root/example as user/password credentials
version: "3.1"
name: "course_planner"

services:
  cp_mongo:
    container_name: cp_mongo
    image: mongo
    restart: "no"
    environment:
      MONGO_INITDB_ROOT_USERNAME: cp_mongo_user
      MONGO_INITDB_ROOT_PASSWORD: hoyiAMud5UaZr2y
      MONGO_INITDB_DATABASE: cp_db
    ports:
      - "27017:27017"
    volumes:
      - cp_mongodb:/data/db
volumes:
  cp_mongodb:
    driver: local
  # cp_mongo_express:
  #   container_name: cp_mongo_express
  #   image: mongo-express
  #   restart: "no"
  #   ports:
  #     - 8081:8081
  #   environment:
  #     ME_CONFIG_MONGODB_ADMINUSERNAME: cp_mongo_user
  #     ME_CONFIG_MONGODB_ADMINPASSWORD: hoyiAMud5UaZr2y
  #     ME_CONFIG_MONGODB_URL: mongodb://cp_mongo_user:hoyiAMud5UaZr2y@mongo:27017/
